development:
  adapter: postgresql
  encoding: unicode
  database: personal_site_rails_development
  pool: 5
  username: jjfisher91
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: personal_site_rails_test
  pool: 5
  username: jjfisher91
  password:
  timeout: 5000
