# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeb4ead96702430ea033a640b0c70491fed38726cd28a6b05f699437bd6b7c065c56f8f9992d9a56ed9db372abded53dbc669920f6c9e4e5c20474d86dcfc60e

test:
  secret_key_base: 33ab2f6d6d3ea223ba59ec7ed605c8854fa13d63b82a594d451b40eadfd5a47e3f2470a7ab56324d6acd8cecf02de71f21eec08d27f2cd481d51d8405c59ece1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
